name: Arnica Dependency Security Scan
description: Scan a repository for dependencies and vulnerabilities
branding:
  icon: upload-cloud
  color: blue
inputs:
  repository-url:
    description: Repository URL associated with the scan
    required: true
  branch:
    description: Branch name associated with the scan
    required: true
    default: main
  scan-path:
    description: Repository path to associate with the scan
    required: false
    default: "."
  api-base-url:
    description: Arnica API base URL (e.g., https://api.app.arnica.io)
    required: false
    default: https://api.app.arnica.io
  scan-timeout-seconds:
    description: Maximum time to wait for scan completion in seconds
    required: false
    default: "900"
  api-token:
    description: Arnica API token (prefer passing via secrets)
    required: false
  on-findings:
    description: Behavior when findings are detected (Failure). One of fail|alert|pass
    required: false
    default: fail
  cdxgen-version:
    description: Version of @cyclonedx/cdxgen to install
    required: false
    default: "11.3.2"
  debug:
    description: Enable verbose API response debug logs
    required: false
    default: "false"
outputs:
  scan-id:
    description: Arnica scan identifier.
    value: ${{ steps.arnica.outputs.scan_id }}
  status:
    description: Final scan status (Success, Failure, Error, Skipped, Timeout)
    value: ${{ steps.arnica.outputs.status }}
runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061
      name: Setup pnpm
      with:
        run_install: false
        version: 10.21.0

    - name: Install node
      uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5

    - name: Install cdxgen
      shell: bash
      run: npm install -g @cyclonedx/cdxgen@${{ inputs.cdxgen-version }}

    - name: Create SBOM
      shell: bash
      env:
        DEBUG: "${{ inputs.debug }}"
        SCAN_PATH: "${{ inputs.scan-path }}"
      run: |
        # Creating SBOM in the scan-path
        set -euo pipefail
        # remove leading slashes if present (path should be relative)
        SCAN_PATH=$(echo "$SCAN_PATH" | sed 's:^/*::')

        cd "$SCAN_PATH"

        if [ "${DEBUG:-false}" = "true" ]; then
          echo "Running cdxgen in debug mode..."
          cdxgen .
          if [ ! -f "bom.json" ]; then
            echo "Error: cdxgen did not create bom.json"
            exit 1
          fi
          cat bom.json | jq '.metadata.tools.components[0]'
        else
          cdxgen . >/dev/null 2>&1
          if [ ! -f "bom.json" ]; then
            echo "Error: cdxgen failed to create SBOM file (bom.json)"
            exit 1
          fi
        fi

        echo "SBOM created successfully at $SCAN_PATH/bom.json"

    - name: Ensure jq is installed
      shell: bash
      run: |
        # Ensure jq is installed
        set -euo pipefail
        if ! command -v jq >/dev/null 2>&1; then
          if command -v apt-get >/dev/null 2>&1; then
            sudo apt-get update -y
            sudo apt-get install -y jq
          else
            echo "jq not found and apt-get is unavailable on this runner. Please install jq."
            exit 1
          fi
        fi

    - name: Upload SBOM to Arnica and wait for scan
      id: arnica
      shell: bash
      env:
        REPO: "${{ inputs.repository-url }}"
        BRANCH: "${{ inputs.branch }}"
        SBOM: "${{ inputs.scan-path }}/bom.json"
        SCAN_PATH: "${{ inputs.scan-path }}"
        API: "${{ inputs.api-base-url }}"
        SCAN_TIMEOUT_SECONDS: "${{ inputs.scan-timeout-seconds }}"
        API_TOKEN_INPUT: "${{ inputs.api-token }}"
        ON_FINDINGS: "${{ inputs.on-findings }}"
        DEBUG: "${{ inputs.debug }}"
      run: ./upload-sbom.sh
