name: Arnica Dependency Security Scan
description: Scan a repository for dependencies and vulnerabilities
branding:
  icon: upload-cloud
  color: blue
inputs:
  repository-url:
    description: Repository URL associated with the scan
    required: true
  branch:
    description: Branch name associated with the scan
    required: true
    default: main
  scan-path:
    description: Repository path to associate with the scan
    required: false
    default: "."
  api-base-url:
    description: Arnica API base URL (e.g., https://api.app.arnica.io)
    required: false
    default: https://api.app.arnica.io
  scan-timeout-seconds:
    description: Maximum time to wait for scan completion in seconds
    required: false
    default: "900"
  api-token:
    description: Arnica API token (prefer passing via secrets)
    required: false
  on-findings:
    description: Behavior when findings are detected (Failure). One of fail|alert|pass
    required: false
    default: fail
  cdxgen-version:
    description: Version of @cyclonedx/cdxgen to install
    required: false
    default: "11.3.2"
  debug:
    description: Enable verbose API response debug logs
    required: false
    default: "false"
outputs:
  scan-id:
    description: Arnica scan identifier.
    value: ${{ steps.arnica.outputs.scan_id }}
  status:
    description: Final scan status (Success, Failure, Error, Skipped, Timeout)
    value: ${{ steps.arnica.outputs.status }}
runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061
      with:
        run_install: false
        version: 10.21.0

    - name: Install node
      uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5

    - name: Install dependencies
      shell: bash
      run: |
        cd $GITHUB_ACTION_PATH
        npm ci

    - name: Install cdxgen
      shell: bash
      run: npm install -g @cyclonedx/cdxgen@${{ inputs.cdxgen-version }}

    - name: Run Arnica dependency scan
      id: arnica
      shell: bash
      env:
        # In composite actions, @actions/core looks for inputs as environment variables with the INPUT_ prefix
        INPUT_REPOSITORY_URL: ${{ inputs.repository-url }}
        INPUT_BRANCH: ${{ inputs.branch }}
        INPUT_SCAN_PATH: ${{ inputs.scan-path }}
        INPUT_API_BASE_URL: ${{ inputs.api-base-url }}
        INPUT_SCAN_TIMEOUT_SECONDS: ${{ inputs.scan-timeout-seconds }}
        INPUT_API_TOKEN: ${{ inputs.api-token }}
        INPUT_ON_FINDINGS: ${{ inputs.on-findings }}
        INPUT_DEBUG: ${{ inputs.debug }}
      run: |
        cd $GITHUB_ACTION_PATH
        npx ts-node src/main.ts
