name: Auto Version on Main

on:
  push:
    branches: [main]
    paths-ignore:
      - "README.md"

jobs:
  tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Bump version and push tag
        id: tagger
        uses: mathieudutour/github-tag-action@a22cf08638b34d5badda920f9daf6e72c477b07b # v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: v
          release_branches: main
          default_bump: patch
          create_annotated_tag: true
          dry_run: false

      - name: Create GitHub Release
        if: steps.tagger.outputs.new_tag
        uses: softprops/action-gh-release@6cbd405e2c4e67a21c47fa9e383d020e4e28b836 # v2.3.0
        with:
          tag_name: ${{ steps.tagger.outputs.new_tag }}
          generate_release_notes: true

      - name: Update major tag (e.g., v1)
        if: steps.tagger.outputs.new_tag
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          TAG_NAME="${{ steps.tagger.outputs.new_tag }}"
          MAJOR_TAG=$(echo "$TAG_NAME" | sed -E 's/^v([0-9]+).*/v\1/')
          echo "Updating $MAJOR_TAG to point to $TAG_NAME"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag -fa "$MAJOR_TAG" -m "Update $MAJOR_TAG tag to $TAG_NAME"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git "$MAJOR_TAG" --force

      - name: Update README to latest version (create branch)
        if: steps.tagger.outputs.new_tag
        shell: bash
        env:
          TAG_NAME: ${{ steps.tagger.outputs.new_tag }}
          DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          git fetch origin
          WORK_BRANCH="docs/readme-${TAG_NAME}"
          git checkout -B "$WORK_BRANCH" "origin/${DEFAULT_BRANCH}"
          if [ -f README.md ]; then
            sed -i.bak -E "s|(uses:\s*[A-Za-z0-9_.-]+/dependency-scan@)[^\s]+|\1${TAG_NAME}|g" README.md
            rm -f README.md.bak
          fi
          if git diff --quiet; then
            echo "README.md already up to date for ${TAG_NAME}."
            exit 0
          fi
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "docs: update README usage to ${TAG_NAME}" || exit 0
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git "$WORK_BRANCH" --force

      - name: Open PR for README update
        if: steps.tagger.outputs.new_tag
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const tag = `${{ toJSON(steps.tagger.outputs.new_tag) }}`.replace(/"/g, '');
            const branch = `docs/readme-${tag}`;
            const base = `${{ toJSON(github.event.repository.default_branch) }}`.replace(/"/g, '');
            const { owner, repo } = context.repo;
            try {
              const { data: pr } = await github.rest.pulls.create({
                owner, repo, head: branch, base,
                title: `docs: update README usage to ${tag}`,
                body: `Automated README update for ${tag}`
              });
              core.summary
                .addHeading('README update PR created')
                .addLink(`#${pr.number}`, pr.html_url)
                .write();
            } catch (e) {
              if (e.status === 422) {
                core.info('PR already exists or branch up to date.');
              } else {
                throw e;
              }
            }

      # Release creation, major tag update, and README bump handled directly in this workflow
