name: Update README usage version

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  bump-readme-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update README to latest release version
        shell: bash
        env:
          TAG_NAME: ${{ github.event.release.tag_name }}
          TARGET_BRANCH: ${{ github.event.release.target_commitish }}
        run: |
          set -euo pipefail

          # Ensure target branch is checked out
          git fetch origin "$TARGET_BRANCH":"$TARGET_BRANCH" || true
          git checkout "$TARGET_BRANCH" || git checkout -B "$TARGET_BRANCH"

          # Update README usage lines to the new tag (any org)
          if [ -f README.md ]; then
            sed -i.bak -E "s|(uses:\s*[A-Za-z0-9_.-]+/dependency-scan@)[^\s]+|\\1${TAG_NAME}|g" README.md
            rm -f README.md.bak
          fi

          # Commit changes only if there are modifications
          if git diff --quiet; then
            echo "README.md already up to date for ${TAG_NAME}."
            exit 0
          fi

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "docs: update README usage to ${TAG_NAME}"
          git push origin "$TARGET_BRANCH"
